language: node_js
node_js:
  - 7
before_install:
  - npm i -g yarn
  - yarn -V
install:
  - yarn
script:
  - npm run lint
  - npm run test:coverage
cache:
  directories:
    - ~/.npm
    - ~/.yarn-cache

